models:  
  - name: Qwen/Qwen3-30B-A3B
    display_name: Qwen3 30B A3B
    description: n/a
    creator_organization_name: Qwen
    access: open
    release_date: 2025-04-29
    tags: [TEXT_MODEL_TAG, LIMITED_FUNCTIONALITY_TEXT_MODEL_TAG, INSTRUCTION_FOLLOWING_MODEL_TAG]
  - name: zai-org/GLM-4.5-Air
    display_name: GLM-4.5-Air
    description: n/a
    creator_organization_name: zai-org
    access: open
    release_date: 2025-04-29
    tags: [TEXT_MODEL_TAG, LIMITED_FUNCTIONALITY_TEXT_MODEL_TAG, INSTRUCTION_FOLLOWING_MODEL_TAG]